<?php
namespace Database\Seeders;
use App\Models\TourPackage;
use Illuminate\Database\Seeder;

class TourPackageSeeder extends Seeder {
    public function run(): void {
        $packages = [
            [
                'package_code' => 'LNC-01',
                'title'        => 'Lombok Signature',
                'subtitle'     => 'The Perfect Introduction to Sasak Culture & Secret Gilis',
                'duration'     => '3 Days / 2 Nights',
                'category'     => 'culture',
                'image_path'   => '/uploads/lombok-signature.jpg',
                'price_per_pax'=> 3746600,
                'min_pax'      => 2,
                'includes'     => ['Private car + fuel + driver', 'Private boat', 'Snorkeling gear', 'Trip documentation', 'Entrance tickets', 'Massage (reflexology)'],
                'excludes'     => ['Hotel (2 nights)', 'Lunch & dinner'],
                'itinerary'    => [
                    ['day'=>'Day 1','title'=>'The Heritage Trail','items'=>['Airport pickup (LOP) — welcome coconut drink in car','Hotel check-in & refresh','14:00 — Desa Sukarara (traditional weaving & traditional dress photo)','14:00 — Desa Sade/Ende (Sasak traditional houses)','16:30 — Pantai Tanjung Aan (pepper-corn white sand)','17:30 — Sunset Trekking Bukit Merese','21:00 — Reflexology massage']],
                    ['day'=>'Day 2','title'=>'The Secret Gilis','items'=>['08:00 — Drive to Pelabuhan Tawun','09:00 — Board private boat','09:30 — Private snorkeling: Gili Nanggu (fruit & coconut water included)','11:30 — Lunch at Gili Sudak seafood (personal expense)','13:00 — Photo stop Gili Kedis','15:30 — Return to hotel']],
                    ['day'=>'Day 3','title'=>'City & Departure','items'=>['09:00 — Souvenir shopping','11:30 — Islamic Center NTB visit','13:15 — Airport drop-off']],
                ],
                'is_active'    => true,
                'is_long_stay' => false,
                'sort_order'   => 1,
            ],
            [
                'package_code' => 'LNC-02',
                'title'        => 'The Sasak Living Heritage',
                'subtitle'     => 'Immersive Cultural Experience & Highland Nature',
                'duration'     => '4 Days / 3 Nights',
                'category'     => 'culture',
                'image_path'   => '/uploads/sasak-living-heritage.jpg',
                'price_per_pax'=> 3718000,
                'min_pax'      => 2,
                'includes'     => ['Transport 4 days', 'Local guide', 'Cultural workshop', 'Massage'],
                'excludes'     => ['Hotel (3 nights)', 'Lunch & dinner'],
                'itinerary'    => [
                    ['day'=>'Day 1','title'=>'Arrival','items'=>['Airport pickup — welcome drink in car','Hotel check-in (Kuta Mandalika)','14:00 — Desa Sukarara & Desa Sade','17:30 — Sunset Trekking Bukit Merese','21:00 — Massage']],
                    ['day'=>'Day 2','title'=>'The Highlands (Tetebatu)','items'=>['09:00 — Drive to Tetebatu','11:00 — Lunch Begibung (Sasak menu, optional)','12:30 — Artisan visit: coffee roasting & VCO coconut oil','14:00 — Rice terrace trek (Rinjani view) & waterfall','16:30 — Return to Kuta hotel']],
                    ['day'=>'Day 3','title'=>'Free Day','items'=>['Beach day: Tanjung Aan','Optional: Sauna / Spa & Wellness']],
                    ['day'=>'Day 4','title'=>'Departure','items'=>['09:00 — Free time','11:00 — Airport transfer']],
                ],
                'is_active'    => true,
                'is_long_stay' => false,
                'sort_order'   => 2,
            ],
            [
                'package_code' => 'LNC-03',
                'title'        => 'Mandalika Legends',
                'subtitle'     => 'Legendary Myths & Pristine Southern Beaches',
                'duration'     => '4 Days / 3 Nights',
                'category'     => 'culture',
                'image_path'   => '/uploads/mandalika-legends.jpg',
                'price_per_pax'=> 2566850,
                'min_pax'      => 2,
                'includes'     => ['Transport', 'Entrance tickets'],
                'excludes'     => ['Hotel', 'Lunch & dinner'],
                'itinerary'    => [
                    ['day'=>'Day 1','title'=>'Check-in & Legend','items'=>['Airport pickup — welcome drink','14:30 — Hotel Kuta check-in','15:30 — Pantai Seger (Princess Mandalika statue & Circuit view)','16:30 — Sunset Bukit Seger + fresh fruit (LNC signature)']],
                    ['day'=>'Day 2','title'=>'Hidden Beaches','items'=>['09:00 — Gua Bangkang "Light of God"','11:30 — Lunch at Pantai Selong Belanak (personal expense)','15:30 — Relaxing at Selong Belanak']],
                    ['day'=>'Day 3','title'=>'Free Day','items'=>['Tanjung Aan beach','Optional: Spa & wellness']],
                    ['day'=>'Day 4','title'=>'Departure','items'=>['09:00 — Desa Banyumulek pottery village','10:30 — Airport transfer']],
                ],
                'is_active'    => true,
                'is_long_stay' => false,
                'sort_order'   => 3,
            ],
            [
                'package_code' => 'LNC-04',
                'title'        => 'Gili Meno Serenity',
                'subtitle'     => 'Honeymoon Vibes, Turtles & Horse Riding',
                'duration'     => '4 Days / 3 Nights',
                'category'     => 'honeymoon',
                'image_path'   => '/uploads/gili-meno-serenity.jpg',
                'price_per_pax'=> 5662800,
                'min_pax'      => 2,
                'includes'     => ['Hotel Senggigi + Gili Meno (2 nights)', 'Speedboat return', 'Private car', 'Horse riding', 'Snorkeling boat', 'Romantic candle-light dinner'],
                'excludes'     => ['Lunch (except dinner D2)', 'Personal expenses'],
                'itinerary'    => [
                    ['day'=>'Day 1','title'=>'Arrival & Relax','items'=>['Airport pickup — welcome drink','12:00 — Drive to Senggigi','14:00 — Hotel check-in Senggigi','17:00 — Sunset at Bukit Malimbu']],
                    ['day'=>'Day 2','title'=>'The Silent Island','items'=>['09:00 — Speedboat to Gili Meno','10:00 — Hotel check-in Meno','10:30 — Snorkeling (statues & turtles)','16:30 — Sunset horse riding on the beach','19:30 — Romantic candle-light dinner (included)']],
                    ['day'=>'Day 3','title'=>'Leisure Day','items'=>['Free time at Gili Meno','Explore beach, read, swim']],
                    ['day'=>'Day 4','title'=>'Departure','items'=>['10:00 — Speedboat back to Lombok → Airport']],
                ],
                'is_active'    => true,
                'is_long_stay' => false,
                'sort_order'   => 4,
            ],
            [
                'package_code' => 'LNC-07',
                'title'        => 'Lombok Surf Retreat',
                'subtitle'     => 'Master the Waves — Private Surf Coaching',
                'duration'     => '3 Days / 2 Nights',
                'category'     => 'adventure',
                'image_path'   => '/uploads/lombok-surf-retreat.jpg',
                'price_per_pax'=> 0,
                'price_label'  => 'Request Quote',
                'min_pax'      => 1,
                'includes'     => ['Private car', 'Certified surf instructor', 'Board rental'],
                'excludes'     => ['Hotel', 'Meals'],
                'itinerary'    => [
                    ['day'=>'Day 1','title'=>'Arrival & First Waves','items'=>['Airport pickup','Hotel check-in Kuta','Afternoon: surf assessment & beginner session at Selong Belanak']],
                    ['day'=>'Day 2','title'=>'Full Surf Day','items'=>['Morning session: technique coaching','Afternoon: free surf at Mawi or Are Guling','Evening: video review with instructor']],
                    ['day'=>'Day 3','title'=>'Final Session & Departure','items'=>['Morning: final surf session','Transfer to airport']],
                ],
                'is_active'    => true,
                'is_long_stay' => false,
                'sort_order'   => 5,
            ],
            [
                'package_code' => 'LNC-13',
                'title'        => 'The Grand Lombok Odyssey',
                'subtitle'     => 'The Ultimate All-in-One Lombok Experience',
                'duration'     => '10 Days / 9 Nights',
                'category'     => 'adventure',
                'image_path'   => '',
                'price_per_pax'=> 0,
                'price_label'  => 'Request Quote',
                'min_pax'      => 2,
                'includes'     => ['Accommodation 9 nights (3 zones)', 'Standby transport', 'Private boat', 'Full guide', '1× lunch Tetebatu', '1× farewell seafood dinner'],
                'excludes'     => ['Most meals (personal expense)', 'International flights'],
                'itinerary'    => [],
                'is_active'    => true,
                'is_long_stay' => true,
                'sort_order'   => 6,
            ],
            [
                'package_code' => 'LNC-14',
                'title'        => 'Slow Travel — Village & Sea',
                'subtitle'     => 'Living Like a Local, Cooking & Traditional Fishing',
                'duration'     => '7 Days / 6 Nights',
                'category'     => 'culture',
                'image_path'   => '',
                'price_per_pax'=> 0,
                'price_label'  => 'Request Quote',
                'min_pax'      => 2,
                'includes'     => ['Transport', 'Local guide', 'Cooking class', 'Fishing session', 'Cultural activities'],
                'excludes'     => ['Hotel', 'Most meals'],
                'itinerary'    => [],
                'is_active'    => true,
                'is_long_stay' => true,
                'sort_order'   => 7,
            ],
            [
                'package_code' => 'BALI-01',
                'title'        => 'Bali Honeymoon Journey',
                'subtitle'     => 'Ubud · Munduk · Jimbaran — 16 Days Private Arrangement',
                'duration'     => '16 Days / 15 Nights',
                'category'     => 'honeymoon',
                'image_path'   => '',
                'price_per_pax'=> 0,
                'price_label'  => 'Request Quote',
                'min_pax'      => 2,
                'includes'     => ['Private car + driver standby 16 days', 'Licensed guide standby 16 days', 'SPA treatments (2× included)', 'VIP beach club access', 'Cooking class'],
                'excludes'     => ['Flights', 'Hotel (3 locations)', 'Most meals'],
                'itinerary'    => [],
                'is_active'    => true,
                'is_long_stay' => true,
                'sort_order'   => 8,
            ],
        ];

        foreach ($packages as $pkg) {
            TourPackage::updateOrCreate(['package_code' => $pkg['package_code']], $pkg);
        }
    }
}
